### ISSUE TITLE
Documenter la limite d'appels

### ISSUE THREAD

**Issue by Flightan** [sgmap/api-particulier-web#2]
Il faudrait documenter la limite de 20 req/s mise en place dans https://github.com/betagouv/api-particulier/issues/44#issuecomment-359791139

**Comment by pknoth** [comment]
je propose de déterminer la limite avant (je pense à AGLAE qui pourrait faire plus si ils réalisent tous leurs appels de la même ip)

**Comment by pknoth** [comment]
connects to https://github.com/betagouv/api-particulier/issues/54
